@startuml AutoDnsRegisterApplication
  
  autonumber

  actor User
  participant nodejs_express as server
  participant GoogleOAuth as oauth
  database MariaDB

  server -> User : give Google OAuth url
  User -> oauth : login
  oauth -> server: redirect
  note left server : authorization_code
  server -> oauth : request tokens
  oauth -> server : give tokens
  note left server : access_token\nrefresh_token
  server -> MariaDB : save access_token and refresh_token

  
@enduml