@startuml database

  package AutoDns  {
    entity Token {
      id : INT <<PK>>
      --
      comment : TEXT (레코드 설명 ex. 'Cloudflare API Token')
      value : TEXT (실제 토큰 등의 값 ex. 123asdf1414)
      createdAt : TIMESTAMP
      updatedAt : TIMESTAMP
    }
    entity Target {
      id : INT <<PK>>
      --
      record : TEXT (타깃 클플 dns 레코드 ex. 'hanwool.com')
      createdAt : TIMESTAMP
      updatedAt : TIMESTAMP
    }
  }

@enduml